float32 x
float32 y
float32 z
float32 vx
float32 vy
float32 vz
float32 ex
float32 ey
float32 ez
float32 thrust
float32 goal_x
float32 goal_y
float32 goal_z
float32 goal_yaw
float32 roll_desired
float32 pitch_desired
float32 kp_xy_outer    # Changed from Kp_xy_outer
float32 kd_xy_outer    # Changed from Kd_xy_outer
float32 kp_xy_inner    # Changed from Kp_xy_inner
float32 kd_xy_inner    # Changed from Kd_xy_inner
float32 kp_z           # Changed from Kp_z
float32 kd_z           # Changed from Kd_z
